# Generated by Django 4.1 on 2023-11-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BiliComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("avid", models.CharField(max_length=255)),
                ("uname", models.CharField(max_length=255)),
                ("current_level", models.IntegerField()),
                ("like", models.IntegerField()),
                ("sex", models.CharField(max_length=10)),
                ("ctime", models.DateTimeField()),
                ("message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="BiliDanmu",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("bvid", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("color", models.CharField(max_length=255)),
                ("fontsize", models.IntegerField()),
                ("midHash", models.CharField(max_length=255)),
                ("mode", models.CharField(max_length=255)),
                ("progress", models.FloatField()),
                ("ctime", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bvid", models.CharField(max_length=30, unique=True)),
                ("avid", models.IntegerField(unique=True)),
                ("oid", models.IntegerField(unique=True)),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("tag", models.CharField(max_length=100)),
                ("vname", models.CharField(max_length=100)),
                ("pubdate", models.DateField()),
                ("pic", models.URLField()),
                ("desc", models.TextField()),
            ],
        ),
    ]
