# Generated by Django 4.1 on 2023-11-16 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("biliscrapy", "0002_remove_video_vname_video_comment_fetched_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bilidanmu", old_name="bvid", new_name="cid",
        ),
    ]
