# Generated by Django 4.1 on 2023-11-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biliscrapy", "0004_rename_video_bilivideo"),
    ]

    operations = [
        migrations.AddField(
            model_name="bilivideo",
            name="comment_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bilivideo",
            name="danmaku_count",
            field=models.IntegerField(default=0),
        ),
    ]
