# Generated by Django 4.1 on 2023-11-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biliscrapy", "0005_bilivideo_comment_count_bilivideo_danmaku_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_code", models.CharField(max_length=100, unique=True)),
                ("expiration_date", models.DateTimeField()),
                (
                    "last_used_address",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
            ],
        ),
    ]
