# Generated by Django 4.1 on 2023-11-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biliscrapy", "0006_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="card", name="is_used", field=models.BooleanField(default=False),
        ),
    ]
